const COMMON_EXCLUDE = [
  "нефть", "дизель", "бензин", "азс", "газ", "уголь", "топлив",
  "бирж", "акци", "курс валют", "криминал", "дтп", "пожар",
  "выбор", "военн", "спорт", "погода",
];

const SOURCES = {
  retail: {
    type: "retail",
    label: "ЦЗС / Ритейл",
    minScore: 32,
    requireRussian: true,
    focusAreas: [
      "розничные сети", "закупки", "поставщики", "FMCG",
      "собственные торговые марки", "маркетплейсы",
      "категорийный менеджмент", "переговоры", "дистрибуция",
    ],
    conclusionLogic: [
      "как это влияет на поставщиков",
      "как это влияет на торговые сети",
      "как это влияет на переговоры и закупочные встречи",
      "как это влияет на будущие события ЦЗС",
    ],
    requiredAny: [
      "ритейл", "розниц", "fmcg", "поставщик", "поставк",
      "закуп", "байер", "торговая сеть", "федеральная сеть",
      "маркетплейс", "стм", "собственная торговая марка",
      "private label", "категори", "промо", "дистриб",
      "логист", "ассортимент", "покупател", "потребител",
    ],
    keywords: [
      "ритейл", "розниц", "fmcg", "товары повседневного спроса",
      "поставщик", "поставк", "закупщик", "закупк", "байер",
      "торговая сеть", "федеральная сеть", "сети", "маркетплейс",
      "онлайн-продаж", "e-commerce", "стм", "собственная торговая марка",
      "private label", "категорийный менеджмент", "категори",
      "переговор", "промо", "логист", "маржинальн", "полка",
      "ассортимент", "дистриб", "покупател", "потребител",
    ],
    exclude: COMMON_EXCLUDE,
    feeds: [
      { name: "Retail.ru",          weight: 10, url: "https://www.retail.ru/rss/" },
      { name: "Retail & Loyalty",   weight: 10, url: "https://retail-loyalty.org/rss/" },
      { name: "New Retail",         weight: 9,  url: "https://new-retail.ru/rss/" },
      { name: "X5 Group",           weight: 8,  url: "https://www.x5.ru/ru/news/feed/" },
      { name: "Магнит",             weight: 8,  url: "https://www.magnit.com/ru/news/rss/" },
      { name: "Ozon News",          weight: 7,  url: "https://corp.ozon.ru/news/rss/" },
      { name: "РБК Бизнес",        weight: 7,  url: "https://rssexport.rbc.ru/rbcnews/news/30/full.rss" },
      { name: "Коммерсантъ",        weight: 7,  url: "https://www.kommersant.ru/RSS/news.xml" },
      { name: "Sostav",             weight: 6,  url: "https://www.sostav.ru/rss/news.xml" },
      { name: "AdIndex",            weight: 6,  url: "https://adindex.ru/rss.xml" },
    ],
  },

  exhibitions: {
    type: "exhibitions",
    label: "Выставки",
    minScore: 18,
    requireRussian: true,
    focusAreas: [
      "выставочная индустрия", "экспоненты", "посетители",
      "деловые мероприятия", "закупочные встречи", "ивент-маркетинг",
      "выставочные форматы", "b2b события",
    ],
    conclusionLogic: [
      "что это значит для выставочных проектов",
      "меняется ли спрос экспонентов или посетителей",
      "нужны ли новые форматы мероприятий",
      "как это может повлиять на будущие выставки компании",
    ],
    requiredAny: [
      "выстав", "экспо", "экспонент", "посетител", "стенд",
      "деловая программа", "закупочные встречи", "мероприят",
      "выставочная индустрия", "организатор", "форум", "конгресс",
      "b2b", "event", "exhibition", "ярмарк", "салон", "показ",
      "выставочный", "выставочного", "павильон",
    ],
    keywords: [
      "выстав", "экспо", "экспонент", "посетител", "стенд",
      "деловая программа", "закупочные встречи", "мероприят",
      "выставочная индустрия", "организатор", "форум", "конгресс",
      "b2b", "ярмарк", "салон", "выставочный", "павильон",
      "международная выставка", "отраслевое мероприятие",
    ],
    exclude: COMMON_EXCLUDE,
    feeds: [
      { name: "EXPOCENTRE",      weight: 10, url: "https://www.expocentr.ru/ru/news/rss/" },
      { name: "ExpoForum",       weight: 9,  url: "https://expoforum.ru/news/rss/" },
      { name: "Expomap",         weight: 9,  url: "https://expomap.ru/rss/" },
      { name: "Продэкспо",       weight: 8,  url: "https://www.prod-expo.ru/ru/rss/" },
      { name: "MVK",             weight: 8,  url: "https://mvk.ru/press/rss/" },
      { name: "Коммерсантъ",    weight: 6,  url: "https://www.kommersant.ru/RSS/news.xml" },
      { name: "РБК",            weight: 6,  url: "https://rssexport.rbc.ru/rbcnews/news/30/full.rss" },
      { name: "ТАСС",           weight: 6,  url: "https://tass.ru/rss/v2.xml" },
      { name: "РИА Новости",    weight: 6,  url: "https://rsshub.app/ria/news" },
      { name: "Sostav Events",   weight: 6,  url: "https://www.sostav.ru/rss/news.xml" },
    ],
  },

  conferences: {
    type: "conferences",
    label: "Конференции",
    minScore: 32,
    requireRussian: true,
    focusAreas: [
      "медицина", "фармацевтика", "медизделия", "регулирование",
      "цифровое здравоохранение", "HR", "рыночные тренды",
    ],
    conclusionLogic: [
      "какие темы становятся важными для конференций",
      "какие темы подходят для конференционных сессий",
      "какие регуляторные изменения стоит обсуждать",
      "какие рыночные тренды стоит учитывать в программах",
    ],
    requiredAny: [
      "медиздел", "медицинск", "здравоохран", "фарма", "фарм",
      "клиник", "регулирован", "регулятор", "маркиров", "регистрац",
      "минздрав", "росздрав", "gxp", "качество", "оборудован",
      "цифровое здравоохранение", "digital health", "vademecum", "remedium",
    ],
    keywords: [
      "медиздел", "медицинск", "здравоохран", "фарма", "фарм",
      "клиник", "регулирован", "регулятор", "маркиров", "регистрац",
      "минздрав", "росздрав", "gxp", "качество", "производств",
      "оборудован", "лаборатор", "пациентск", "цифровизац",
      "digital health", "hr", "кадры", "медицинский рынок",
      "vademecum", "remedium",
    ],
    exclude: [
      ...COMMON_EXCLUDE,
      "яровая", "вице-спикер", "госдума заявила", "скандал", "суд",
    ],
    feeds: [
      { name: "Фармвестник",    weight: 10, url: "https://pharmvestnik.ru/rss/news/" },
      { name: "Vademecum",      weight: 10, url: "https://vademec.ru/rss/news/" },
      { name: "Remedium",       weight: 9,  url: "https://remedium.ru/rss/" },
      { name: "Медвестник",     weight: 9,  url: "https://medvestnik.ru/rss/" },
      { name: "Минздрав РФ",   weight: 10, url: "https://minzdrav.gov.ru/rss" },
      { name: "Росздравнадзор", weight: 10, url: "https://roszdravnadzor.gov.ru/rss" },
      { name: "РБК Здоровье",  weight: 7,  url: "https://rssexport.rbc.ru/rbcnews/news/30/full.rss" },
      { name: "Коммерсантъ",   weight: 7,  url: "https://www.kommersant.ru/RSS/news.xml" },
    ],
  },

  ai: {
    type: "ai",
    label: "ИИ",
    minScore: 28,
    requireRussian: false,
    focusAreas: [
      "AI-агенты", "автоматизация", "продуктивность",
      "языковые модели", "внутренние процессы", "бизнес-применения",
    ],
    conclusionLogic: [
      "как это может использоваться внутри компании",
      "какие отделы могут получить пользу",
      "может ли это автоматизировать рутинную работу",
      "может ли это повысить продуктивность",
      "заслуживает ли это тестирования",
    ],
    requiredAny: [
      "искусственн", "нейросет", "openai", "anthropic", "deepmind",
      "chatgpt", "gpt", "llm", "ai agent", "ai agents",
      "artificial intelligence", "machine learning", "генеративн",
      "автоматизац", "copilot", "assistant", "ии", "нейронн",
    ],
    keywords: [
      "искусственн", "нейросет", "openai", "anthropic", "deepmind",
      "microsoft ai", "chatgpt", "gpt", "llm", "ai agent", "ai agents",
      "artificial intelligence", "machine learning", "модель", "агент",
      "генеративн", "автоматизац", "productivity", "workflow",
      "copilot", "assistant", "нейронн", "большая языковая",
    ],
    exclude: [
      ...COMMON_EXCLUDE,
      "криптовалют",
    ],
    feeds: [
      { name: "VC.ru ИИ",          weight: 10, url: "https://vc.ru/rss" },
      { name: "Habr ИИ",           weight: 9,  url: "https://habr.com/ru/rss/hub/artificial_intelligence/articles/" },
      { name: "Habr ML",           weight: 8,  url: "https://habr.com/ru/rss/hub/machine_learning/articles/" },
      { name: "CNews Технологии",  weight: 8,  url: "https://www.cnews.ru/inc/rss/cnews_all.xml" },
      { name: "OpenAI News",       weight: 10, url: "https://openai.com/news/rss.xml" },
      { name: "Anthropic News",    weight: 10, url: "https://www.anthropic.com/news/rss.xml" },
      { name: "Google DeepMind",   weight: 9,  url: "https://deepmind.google/discover/blog/rss.xml" },
      { name: "Microsoft AI Blog", weight: 8,  url: "https://blogs.microsoft.com/ai/feed/" },
      { name: "РБК Технологии",   weight: 7,  url: "https://rssexport.rbc.ru/rbcnews/news/30/full.rss" },
    ],
  },
};

module.exports = { SOURCES };
