const SOURCES = {
  retail: {
    label: "ЦЗС / Ритейл",
    keywords: [
      "ритейл",
      "розниц",
      "fmcg",
      "поставщик",
      "поставк",
      "сеть",
      "сети",
      "маркетплейс",
      "онлайн",
      "продукт",
      "закуп",
      "стм",
      "цена",
      "промо",
      "логист",
    ],
    feeds: [
      { name: "Retail.ru", url: "https://www.retail.ru/rss/all.xml" },
      { name: "РБК", url: "https://rssexport.rbc.ru/rbcnews/news/30/full.rss" },
      { name: "Коммерсантъ", url: "https://www.kommersant.ru/RSS/news.xml" },
      { name: "ТАСС", url: "https://tass.ru/rss/v2.xml" },
    ],
  },
  exhibitions: {
    label: "Выставки",
    keywords: [
      "выстав",
      "экспо",
      "экспонент",
      "посетител",
      "форум",
      "производител",
      "поставщик",
      "промышлен",
      "агро",
      "пищев",
      "рынок",
      "участник",
      "деловая программа",
    ],
    feeds: [
      { name: "ExpoMap", url: "https://expomap.ru/rss/" },
      { name: "РБК", url: "https://rssexport.rbc.ru/rbcnews/news/30/full.rss" },
      { name: "Коммерсантъ", url: "https://www.kommersant.ru/RSS/news.xml" },
      { name: "ТАСС", url: "https://tass.ru/rss/v2.xml" },
    ],
  },
  conferences: {
    label: "Конференции",
    keywords: [
      "здрав",
      "медицин",
      "медиздел",
      "фарма",
      "клиник",
      "регулирован",
      "регулятор",
      "производств",
      "качество",
      "маркиров",
      "рынок",
      "пациент",
      "врач",
    ],
    feeds: [
      { name: "Медвестник", url: "https://medvestnik.ru/rss/" },
      { name: "Фармвестник", url: "https://pharmvestnik.ru/rss/news/" },
      { name: "РБК", url: "https://rssexport.rbc.ru/rbcnews/news/30/full.rss" },
      { name: "ТАСС", url: "https://tass.ru/rss/v2.xml" },
    ],
  },
  ai: {
    label: "ИИ",
    keywords: [
      "ии",
      "ai",
      "искусственн",
      "нейросет",
      "openai",
      "модель",
      "агент",
      "робот",
      "автоматизац",
      "технолог",
      "machine learning",
      "artificial intelligence",
    ],
    feeds: [
      { name: "OpenAI", url: "https://openai.com/news/rss.xml" },
      { name: "The Verge", url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml" },
      { name: "РБК", url: "https://rssexport.rbc.ru/rbcnews/news/30/full.rss" },
      { name: "Коммерсантъ", url: "https://www.kommersant.ru/RSS/news.xml" },
      { name: "ТАСС", url: "https://tass.ru/rss/v2.xml" },
    ],
  },
};

module.exports = { SOURCES };
