const COMMON_EXCLUDE = [
  "нефть", "дизель", "бензин", "азс", "газ", "уголь", "топлив",
  "бирж", "акци", "курс валют", "криминал", "дтп", "пожар",
  "выбор", "военн", "спорт", "погода",
];

const TRUSTED_DOMAINS = {
  retail: [
    ["retail.ru", 10], ["new-retail.ru", 10], ["retail-loyalty.org", 10], ["shoppers.media", 9],
    ["sostav.ru", 7], ["adindex.ru", 7], ["e-pepper.ru", 8], ["oborot.ru", 7],
    ["dairynews.today", 8], ["milknews.ru", 8], ["agroinvestor.ru", 8], ["fruitnews.ru", 7],
    ["meatinfo.ru", 6], ["fishnews.ru", 6], ["alcoexpert.ru", 5], ["unipack.ru", 6],
    ["честныйзнак.рф", 9], ["xn--80ajghhoc2aj1c8b.xn--p1ai", 9], ["acort.ru", 10], ["akit.ru", 8], ["rusprodsoyuz.ru", 8],
    ["souzmoloko.ru", 8], ["rusbrand.com", 6], ["x5.ru", 8], ["magnit.com", 8],
    ["lenta.com", 7], ["metro-cc.ru", 6], ["auchan.ru", 6], ["fix-price.com", 6],
    ["corp.ozon.ru", 8], ["wildberries.ru", 8], ["market.yandex.ru", 6],
    ["mvideoeldorado.ru", 5], ["dns-shop.ru", 5], ["vseinstrumenti.ru", 5],
    ["lemanapro.ru", 5], ["hoff.ru", 5], ["infoline.spb.ru", 8], ["nielseniq.com", 8],
    ["gfk.com", 7], ["datainsight.ru", 8], ["romir.ru", 6], ["kommersant.ru", 5],
    ["vedomosti.ru", 5], ["rbc.ru", 4], ["cnews.ru", 5], ["nspk.ru", 3],
  ],
  exhibitions: [
    ["expomap.ru", 10], ["expoforum-center.ru", 10], ["expoforum.ru", 10], ["expocentr.ru", 10], ["ruef.ru", 10],
    ["ufi.org", 8], ["aeo.org.uk", 7], ["event-live.ru", 7], ["event.ru", 7],
    ["world-food.ru", 9], ["prod-expo.ru", 9], ["peterfood.ru", 10], ["nevabuyersweek.ru", 10],
    ["agroprodmash-expo.ru", 8], ["rosupack.com", 8], ["meatindustry.ru", 7],
    ["dairytech-expo.ru", 7], ["seafoodexporussia.com", 7], ["interfood-expo.ru", 7],
    ["pirexpo.com", 6], ["coffeeteacacaoexpo.ru", 5], ["modern-bakery.ru", 5],
    ["pharmtech-expo.ru", 6], ["zdravo-expo.ru", 6], ["mosbuild.com", 6],
    ["interlight-building.ru", 5], ["hhexpo.ru", 8], ["kidsrussia.ru", 5],
    ["mirdetstva-expo.ru", 5], ["skrepkaexpo.ru", 5], ["buybrandexpo.com", 3],
    ["cpm-moscow.com", 5], ["heimtextil-russia.ru", 4], ["meb-expo.ru", 7],
    ["mebelshik.biz", 5], ["flowers-expo.ru", 7], ["minpromtorg.gov.ru", 6],
    ["tpprf.ru", 6], ["exportcenter.ru", 6], ["exhibitionnews.uk", 7],
    ["tsnn.com", 7], ["exhibitionworld.co.uk", 8],
  ],
  conferences: [
    ["vademec.ru", 10], ["pharmvestnik.ru", 10], ["remedium.ru", 9], ["medvestnik.ru", 9],
    ["gxpnews.net", 9], ["katrenstyle.ru", 6], ["minzdrav.gov.ru", 10],
    ["roszdravnadzor.gov.ru", 10], ["minpromtorg.gov.ru", 8], ["government.ru", 6],
    ["duma.gov.ru", 4], ["council.gov.ru", 3], ["regulation.gov.ru", 10],
    ["grls.rosminzdrav.ru", 6], ["eec.eaeunion.org", 8], ["rbc.ru", 6],
    ["kommersant.ru", 8], ["vedomosti.ru", 8], ["rg.ru", 6], ["interfax.ru", 6],
    ["tass.ru", 6], ["aipm.org", 8], ["arfp.ru", 8], ["spfo.ru", 6],
    ["acto-russia.org", 7], ["sechenov.ru", 5], ["ffoms.gov.ru", 7], ["vshouz.ru", 6],
    ["mednet.ru", 7], ["hse.ru", 5], ["medtecheurope.org", 7], ["fda.gov", 7],
    ["ema.europa.eu", 7], ["who.int", 5], ["fiercepharma.com", 6],
    ["fiercehealthcare.com", 5], ["pharmatimes.com", 5], ["biopharmadive.com", 6],
    ["medcitynews.com", 5], ["healthcareitnews.com", 5], ["himss.org", 5],
    ["digitalhealth.net", 5], ["beckershospitalreview.com", 3], ["thelancet.com", 3],
  ],
  ai: [
    ["openai.com", 10], ["anthropic.com", 10], ["deepmind.google", 10], ["blog.google", 9],
    ["blogs.microsoft.com", 9], ["microsoft.com", 8], ["ai.meta.com", 9], ["blogs.nvidia.com", 9],
    ["aws.amazon.com", 8], ["cloud.google.com", 8], ["azure.microsoft.com", 8],
    ["research.ibm.com", 6], ["salesforce.com", 7], ["blog.adobe.com", 6],
    ["huggingface.co", 9], ["mistral.ai", 8], ["cohere.com", 7], ["perplexity.ai", 6],
    ["blog.langchain.com", 8], ["llamaindex.ai", 8], ["pinecone.io", 6], ["weaviate.io", 6],
    ["replicate.com", 5], ["techcrunch.com", 9], ["theverge.com", 8], ["venturebeat.com", 8],
    ["the-decoder.com", 8], ["technologyreview.com", 8], ["wired.com", 6],
    ["spectrum.ieee.org", 6], ["arstechnica.com", 6], ["zdnet.com", 6],
    ["theinformation.com", 4], ["semafor.com", 5], ["cnbc.com", 4], ["reuters.com", 5],
    ["bloomberg.com", 4], ["ft.com", 4], ["habr.com", 7], ["vc.ru", 5],
    ["tadviser.ru", 7], ["cnews.ru", 7], ["comnews.ru", 5], ["rbc.ru", 6],
    ["kommersant.ru", 6], ["vedomosti.ru", 6], ["hai.stanford.edu", 5],
  ],
};

const SOURCES = {
  retail: {
    type: "retail",
    label: "ЦЗС / Ритейл",
    minScore: 32,
    requireRussian: true,
    focusAreas: [
      "розничные сети", "закупки", "поставщики", "FMCG",
      "собственные торговые марки", "маркетплейсы",
      "категорийный менеджмент", "переговоры", "дистрибуция",
    ],
    conclusionLogic: [
      "как это влияет на поставщиков",
      "как это влияет на торговые сети",
      "как это влияет на переговоры и закупочные встречи",
      "как это влияет на будущие события ЦЗС",
    ],
    ddgsRegion: "ru-ru",
    ddgsWeight: 9,
    trustedDomains: TRUSTED_DOMAINS.retail,
    domainSearchTerm: "ритейл поставщики сети закупки FMCG",
    searchQueries: [
      "ритейл поставщики торговые сети закупки FMCG",
      "собственные торговые марки СТМ ритейл поставщики",
      "переговоры с торговыми сетями поставщики закупщики",
      "маркетплейсы ритейл поставщики FMCG",
      "category management ритейл закупки поставщики",
      "Retail.ru поставщики сети закупки",
    ],
    requiredAny: [
      "ритейл", "розниц", "fmcg", "поставщик", "поставк",
      "закуп", "байер", "торговая сеть", "федеральная сеть",
      "маркетплейс", "стм", "собственная торговая марка",
      "private label", "категори", "промо", "дистриб",
      "логист", "ассортимент", "покупател", "потребител",
    ],
    keywords: [
      "ритейл", "розниц", "fmcg", "товары повседневного спроса",
      "поставщик", "поставк", "закупщик", "закупк", "байер",
      "торговая сеть", "федеральная сеть", "сети", "маркетплейс",
      "онлайн-продаж", "e-commerce", "стм", "собственная торговая марка",
      "private label", "категорийный менеджмент", "категори",
      "переговор", "промо", "логист", "маржинальн", "полка",
      "ассортимент", "дистриб", "покупател", "потребител",
    ],
    exclude: COMMON_EXCLUDE,
    feeds: [
      { name: "Retail.ru",          weight: 10, url: "https://www.retail.ru/rss/" },
      { name: "Retail & Loyalty",   weight: 10, url: "https://retail-loyalty.org/rss/" },
      { name: "New Retail",         weight: 9,  url: "https://new-retail.ru/rss/" },
      { name: "AdIndex",            weight: 8,  url: "https://adindex.ru/rss.xml" },
      { name: "Sostav",             weight: 8,  url: "https://www.sostav.ru/rss/news.xml" },
      { name: "X5 Group Newsroom",  weight: 8,  url: "https://www.x5.ru/ru/news/feed/" },
      { name: "Магнит Новости",     weight: 8,  url: "https://www.magnit.com/ru/news/rss/" },
      { name: "Лента Новости",      weight: 7,  url: "https://lenta.com/rss/" },
      { name: "Ozon News",          weight: 7,  url: "https://corp.ozon.ru/news/rss/" },
      { name: "Wildberries News",   weight: 7,  url: "https://www.wildberries.ru/services/rss" },
    ],
  },

  exhibitions: {
    type: "exhibitions",
    label: "Выставки",
    minScore: 20,
    requireRussian: true,
    focusAreas: [
      "выставочная индустрия", "экспоненты", "посетители",
      "деловые мероприятия", "закупочные встречи", "ивент-маркетинг",
      "выставочные форматы", "b2b события",
    ],
    conclusionLogic: [
      "что это значит для выставочных проектов",
      "меняется ли спрос экспонентов или посетителей",
      "нужны ли новые форматы мероприятий",
      "как это может повлиять на будущие выставки компании",
    ],
    ddgsRegion: "ru-ru",
    ddgsWeight: 8,
    trustedDomains: TRUSTED_DOMAINS.exhibitions,
    specialistSourceMinWeight: 9,
    domainSearchTerm: "выставки экспоненты посетители деловая программа",
    searchQueries: [
      "выставки экспоненты посетители деловая программа B2B",
      "выставочный рынок Россия экспоненты посетители",
      "закупочные встречи выставка поставщики ритейл",
      "Петерфуд поставщики закупщики выставка",
      "Продэкспо экспоненты посетители деловая программа",
      "WorldFood Moscow экспоненты посетители",
      "HouseHold Expo экспоненты посетители non-food",
      "выставочная индустрия экспоненты посетители b2b мероприятия",
      "продовольственные выставки экспоненты посетители деловая программа",
      "non-food выставка поставщики закупочные встречи",
      "выставки food non-food тренды экспоненты посетители",
      "выставки Петербург экспоненты деловая программа",
      "UFI exhibition industry visitor demand exhibitors",
    ],
    requiredAny: [
      "выстав", "экспо", "экспонент", "посетител", "стенд",
      "деловая программа", "закупочные встречи", "мероприят",
      "выставочная индустрия", "организатор", "форум", "конгресс",
      "b2b", "event", "exhibition", "trade show", "ярмарк",
      "ufi", "aeo", "visitor demand", "exhibitor demand",
    ],
    keywords: [
      "выстав", "экспо", "экспонент", "посетител", "стенд",
      "деловая программа", "закупочные встречи", "мероприят",
      "выставочная индустрия", "организатор", "форум", "конгресс",
      "b2b", "event marketing", "exhibition", "trade show",
      "visitor demand", "exhibitor demand", "ufi", "aeo",
    ],
    exclude: COMMON_EXCLUDE,
    feeds: [
      { name: "Expomap",          weight: 10, url: "https://expomap.ru/rss/" },
      { name: "ExpoForum News",   weight: 9,  url: "https://expoforum-center.ru/ru/news/rss/" },
      { name: "ITE Group News",   weight: 9,  url: "https://www.ite.group/media/rss/" },
      { name: "EXPOCENTRE News",  weight: 9,  url: "https://www.expocentr.ru/ru/news/rss/" },
      { name: "UFI",              weight: 8,  url: "https://www.ufi.org/feed/" },
      { name: "AEO",              weight: 7,  url: "https://www.aeo.org.uk/rss/news" },
    ],
    htmlSources: [
      {
        name: "Expomap",
        weight: 10,
        url: "https://expomap.ru/news/",
        include: ["/news/"],
        exclude: ["/news/theme/", "/news/tag/"],
        limit: 30,
      },
      {
        name: "ExpoForum News",
        weight: 9,
        url: "https://expoforum-center.ru/ru/news/",
        include: ["/news/"],
        exclude: ["/press/", "/info_center/"],
        limit: 20,
      },
      {
        name: "EXPOCENTRE News",
        weight: 9,
        url: "https://www.expocentr.ru/ru/news/",
        include: ["/ru/news/"],
        exclude: [],
        limit: 20,
      },
    ],
  },

  conferences: {
    type: "conferences",
    label: "Конференции",
    minScore: 32,
    requireRussian: true,
    focusAreas: [
      "медицина", "фармацевтика", "медизделия", "регулирование",
      "цифровое здравоохранение", "HR", "рыночные тренды",
    ],
    conclusionLogic: [
      "какие темы становятся важными для конференций",
      "какие темы подходят для конференционных сессий",
      "какие регуляторные изменения стоит обсуждать",
      "какие рыночные тренды стоит учитывать в программах",
    ],
    ddgsRegion: "ru-ru",
    ddgsWeight: 9,
    trustedDomains: TRUSTED_DOMAINS.conferences,
    specialistSourceMinWeight: 9,
    domainSearchTerm: "медизделия фарма регулирование здравоохранение",
    searchQueries: [
      "медицинские изделия регулирование конференция программа",
      "медизделия регистрация маркировка качество Росздравнадзор",
      "фарма рынок регулирование конференция темы",
      "здравоохранение цифровизация клиники рынок",
      "Vademecum медизделия фарма регулирование",
      "Фармвестник фармацевтический рынок регулирование",
      "медизделия регулирование регистрация Росздравнадзор Минздрав",
      "фармацевтический рынок регулирование конференция",
      "цифровое здравоохранение клиники регулирование рынок",
      "медицинские изделия маркировка регистрация качество",
      "Vademecum медизделия регулирование здравоохранение",
      "Фармвестник фарма рынок регулирование",
    ],
    requiredAny: [
      "медиздел", "медицинск", "здравоохран", "фарма", "фарм",
      "клиник", "регулирован", "регулятор", "маркиров", "регистрац",
      "минздрав", "росздрав", "gxp", "качество", "оборудован",
      "цифровое здравоохранение", "digital health", "vademecum", "remedium",
    ],
    keywords: [
      "медиздел", "медицинск", "здравоохран", "фарма", "фарм",
      "клиник", "регулирован", "регулятор", "маркиров", "регистрац",
      "минздрав", "росздрав", "gxp", "качество", "производств",
      "оборудован", "лаборатор", "пациентск", "цифровизац",
      "digital health", "hr", "кадры", "медицинский рынок",
      "vademecum", "remedium",
    ],
    exclude: [
      ...COMMON_EXCLUDE,
      "яровая", "вице-спикер", "госдума заявила", "скандал", "суд",
    ],
    feeds: [
      { name: "Фармвестник",          weight: 10, url: "https://pharmvestnik.ru/rss/news/" },
      { name: "Vademecum",            weight: 10, url: "https://vademec.ru/rss/news/" },
      { name: "Remedium",             weight: 9,  url: "https://remedium.ru/rss/" },
      { name: "Медвестник",           weight: 9,  url: "https://medvestnik.ru/rss/" },
      { name: "Минздрав РФ",         weight: 10, url: "https://minzdrav.gov.ru/rss" },
      { name: "Росздравнадзор",       weight: 10, url: "https://roszdravnadzor.gov.ru/rss" },
    ],
  },

  ai: {
    type: "ai",
    label: "ИИ",
    minScore: 28,
    requireRussian: true,
    focusAreas: [
      "AI-агенты", "автоматизация", "продуктивность",
      "языковые модели", "внутренние процессы", "бизнес-применения",
    ],
    conclusionLogic: [
      "как это может использоваться внутри компании",
      "какие отделы могут получить пользу",
      "может ли это автоматизировать рутинную работу",
      "может ли это повысить продуктивность",
      "заслуживает ли это тестирования",
    ],
    ddgsRegion: "ru-ru",
    ddgsWeight: 9,
    trustedDomains: TRUSTED_DOMAINS.ai,
    domainSearchTerm: "искусственный интеллект бизнес автоматизация",
    searchQueries: [
      "искусственный интеллект бизнес автоматизация процессы нейросети",
      "ИИ агенты автоматизация бизнеса рабочие процессы",
      "нейросети для бизнеса автоматизация сотрудников",
      "OpenAI искусственный интеллект бизнес автоматизация",
      "Хабр искусственный интеллект нейросети бизнес",
      "CNews искусственный интеллект бизнес",
      "AI agents business automation internal workflows",
      "OpenAI AI agent enterprise productivity",
      "Anthropic Claude enterprise automation workflows",
      "Microsoft AI Copilot business processes productivity",
      "LLM agents workplace automation business",
      "генеративный ИИ автоматизация бизнес процессы",
    ],
    requiredAny: [
      "искусственн", "нейросет", "openai", "anthropic", "deepmind",
      "chatgpt", "gpt", "llm", "ai agent", "ai agents",
      "artificial intelligence", "machine learning", "генеративн",
      "автоматизац", "copilot", "assistant",
    ],
    keywords: [
      "искусственн", "нейросет", "openai", "anthropic", "deepmind",
      "microsoft ai", "chatgpt", "gpt", "llm", "ai agent", "ai agents",
      "artificial intelligence", "machine learning", "модель", "агент",
      "генеративн", "автоматизац", "productivity", "workflow",
      "business applications", "internal processes", "copilot", "assistant",
    ],
    exclude: [
      ...COMMON_EXCLUDE,
      "криптовалют",
    ],
    feeds: [
      { name: "CNews AI",          weight: 8,  url: "https://www.cnews.ru/inc/rss/news.xml" },
      { name: "Хабр AI",           weight: 8,  url: "https://habr.com/ru/rss/hub/artificial_intelligence/articles/" },
      { name: "TAdviser",          weight: 7,  url: "https://www.tadviser.ru/rss.xml" },
      { name: "РБК Технологии",    weight: 6,  url: "https://rssexport.rbc.ru/rbcnews/news/technology/full.rss" },
      { name: "OpenAI News",        weight: 10, url: "https://openai.com/news/rss.xml" },
      { name: "Anthropic News",     weight: 10, url: "https://www.anthropic.com/news/rss.xml" },
      { name: "Google DeepMind Blog", weight: 10, url: "https://deepmind.google/discover/blog/rss.xml" },
      { name: "Microsoft AI Blog",  weight: 9,  url: "https://blogs.microsoft.com/ai/feed/" },
      { name: "TechCrunch AI",      weight: 9,  url: "https://techcrunch.com/category/artificial-intelligence/feed/" },
      { name: "The Verge AI",       weight: 8,  url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml" },
      { name: "VentureBeat AI",     weight: 8,  url: "https://venturebeat.com/category/ai/feed/" },
    ],
  },
};

module.exports = { SOURCES };
