const COMMON_EXCLUDE = [
  "нефть",
  "дизель",
  "бензин",
  "азс",
  "газ",
  "уголь",
  "топлив",
  "бирж",
  "акци",
  "курс валют",
  "криминал",
  "дтп",
  "пожар",
  "выбор",
  "военн",
  "спорт",
  "погода",
];

const SOURCES = {
  retail: {
    type: "retail",
    label: "ЦЗС / Ритейл",
    minScore: 42,
    focusAreas: [
      "retail chains",
      "buyers",
      "suppliers",
      "fmcg",
      "private labels",
      "marketplaces",
      "category management",
      "negotiations",
      "distribution",
    ],
    conclusionLogic: [
      "как это влияет на поставщиков",
      "как это влияет на торговые сети",
      "как это влияет на переговоры",
      "как это влияет на закупочные встречи",
      "как это влияет на будущие события ЦЗС",
    ],
    requiredAny: [
      "ритейл",
      "розниц",
      "fmcg",
      "поставщик",
      "поставк",
      "закуп",
      "байер",
      "торговая сеть",
      "федеральная сеть",
      "маркетплейс",
      "стм",
      "собственная торговая марка",
      "private label",
      "категори",
      "промо",
      "дистриб",
      "логист",
      "ассортимент",
    ],
    keywords: [
      "ритейл",
      "розниц",
      "fmcg",
      "товары повседневного спроса",
      "поставщик",
      "поставк",
      "закупщик",
      "закупк",
      "байер",
      "торговая сеть",
      "федеральная сеть",
      "сети",
      "маркетплейс",
      "онлайн-продаж",
      "e-commerce",
      "стм",
      "собственная торговая марка",
      "private label",
      "категорийный менеджмент",
      "категори",
      "переговор",
      "промо",
      "логист",
      "маржинальн",
      "полка",
      "ассортимент",
      "дистриб",
    ],
    exclude: COMMON_EXCLUDE,
    feeds: [
      { name: "Retail.ru", weight: 10, url: "https://www.retail.ru/rss/" },
      { name: "Retail & Loyalty", weight: 10, url: "https://retail-loyalty.org/rss/" },
      { name: "New Retail", weight: 9, url: "https://new-retail.ru/rss/" },
      { name: "AdIndex", weight: 8, url: "https://adindex.ru/rss.xml" },
      { name: "Sostav", weight: 8, url: "https://www.sostav.ru/rss/news.xml" },
      { name: "X5 Group Newsroom", weight: 8, url: "https://www.x5.ru/ru/news/feed/" },
      { name: "Магнит Новости", weight: 8, url: "https://www.magnit.com/ru/news/rss/" },
      { name: "Лента Новости", weight: 7, url: "https://lenta.com/rss/" },
      { name: "Ozon News", weight: 7, url: "https://corp.ozon.ru/news/rss/" },
      { name: "Wildberries News", weight: 7, url: "https://www.wildberries.ru/services/rss" },
    ],
  },

  exhibitions: {
    type: "exhibitions",
    label: "Выставки",
    minScore: 42,
    focusAreas: [
      "exhibitors",
      "visitors",
      "exhibition industry",
      "b2b events",
      "procurement meetings",
      "event marketing",
    ],
    conclusionLogic: [
      "что это значит для выставочных проектов",
      "меняется ли спрос экспонентов",
      "меняется ли спрос посетителей",
      "нужны ли новые форматы мероприятий",
      "как это может повлиять на будущие выставки компании",
    ],
    requiredAny: [
      "выстав",
      "экспо",
      "экспонент",
      "посетител",
      "стенд",
      "деловая программа",
      "закупочные встречи",
      "b2b",
      "event",
      "exhibition",
      "trade show",
      "procurement meetings",
      "visitor demand",
      "exhibitor demand",
      "мероприят",
      "выставочная индустрия",
      "ufi",
      "aeo",
    ],
    keywords: [
      "выстав",
      "экспо",
      "экспонент",
      "посетител",
      "стенд",
      "деловая программа",
      "закупочные встречи",
      "b2b",
      "event marketing",
      "exhibition",
      "trade show",
      "procurement meetings",
      "visitor demand",
      "exhibitor demand",
      "организатор",
      "мероприят",
      "конгресс",
      "форум",
      "выставочная индустрия",
      "ufi",
      "aeo",
    ],
    exclude: COMMON_EXCLUDE,
    feeds: [
      { name: "Expomap", weight: 10, url: "https://expomap.ru/rss/" },
      { name: "ExpoForum News", weight: 9, url: "https://expoforum-center.ru/ru/news/rss/" },
      { name: "ITE Group News", weight: 9, url: "https://www.ite.group/media/rss/" },
      { name: "EXPOCENTRE News", weight: 9, url: "https://www.expocentr.ru/ru/news/rss/" },
      { name: "UFI", weight: 8, url: "https://www.ufi.org/feed/" },
      { name: "AEO", weight: 7, url: "https://www.aeo.org.uk/rss/news" },
    ],
  },

  conferences: {
    type: "conferences",
    label: "Конференции",
    minScore: 44,
    focusAreas: [
      "medicine",
      "pharma",
      "medical devices",
      "regulation",
      "digital healthcare",
      "hr",
      "market trends",
    ],
    conclusionLogic: [
      "какие темы становятся важными",
      "какие темы подходят для конференционных сессий",
      "какие регуляторные изменения стоит обсуждать",
      "какие рыночные тренды стоит учитывать в будущих программах",
    ],
    requiredAny: [
      "медиздел",
      "медицинск",
      "здравоохран",
      "фарма",
      "фарм",
      "клиник",
      "регулирован",
      "регулятор",
      "маркиров",
      "регистрац",
      "минздрав",
      "росздрав",
      "gxp",
      "качество",
      "оборудован",
      "цифровое здравоохранение",
      "digital health",
      "vademecum",
      "remedium",
    ],
    keywords: [
      "медиздел",
      "медицинск",
      "здравоохран",
      "фарма",
      "фарм",
      "клиник",
      "регулирован",
      "регулятор",
      "маркиров",
      "регистрац",
      "минздрав",
      "росздрав",
      "gxp",
      "качество",
      "производств",
      "оборудован",
      "лаборатор",
      "пациентск",
      "цифровизац",
      "digital health",
      "hr",
      "кадры",
      "медицинский рынок",
      "vademecum",
      "remedium",
    ],
    exclude: [
      ...COMMON_EXCLUDE,
      "яровая",
      "вице-спикер",
      "прием врача должен",
      "не должны тратить много времени",
      "госдума заявила",
      "скандал",
      "суд",
    ],
    feeds: [
      { name: "Фармвестник", weight: 10, url: "https://pharmvestnik.ru/rss/news/" },
      { name: "Vademecum", weight: 10, url: "https://vademec.ru/rss/news/" },
      { name: "Remedium", weight: 9, url: "https://remedium.ru/rss/" },
      { name: "Медвестник", weight: 9, url: "https://medvestnik.ru/rss/" },
      { name: "Минздрав РФ", weight: 10, url: "https://minzdrav.gov.ru/rss" },
      { name: "Росздравнадзор", weight: 10, url: "https://roszdravnadzor.gov.ru/rss" },
      { name: "РБК Здравоохранение", weight: 8, url: "https://rssexport.rbc.ru/rbcnews/news/30/full.rss" },
      { name: "Коммерсантъ Фарма", weight: 8, url: "https://www.kommersant.ru/RSS/news.xml" },
    ],
  },

  ai: {
    type: "ai",
    label: "ИИ",
    minScore: 42,
    focusAreas: [
      "ai agents",
      "automation",
      "productivity",
      "llms",
      "internal processes",
      "business applications",
    ],
    conclusionLogic: [
      "как это может использоваться внутри компании",
      "какие отделы могут получить пользу",
      "может ли это автоматизировать рутинную работу",
      "может ли это повысить продуктивность",
      "заслуживает ли это тестирования",
    ],
    requiredAny: [
      "искусственн",
      "нейросет",
      "openai",
      "anthropic",
      "deepmind",
      "chatgpt",
      "gpt",
      "llm",
      "ai agent",
      "ai agents",
      "artificial intelligence",
      "machine learning",
      "генеративн",
      "автоматизац",
      "copilot",
      "assistant",
    ],
    keywords: [
      "искусственн",
      "нейросет",
      "openai",
      "anthropic",
      "deepmind",
      "microsoft ai",
      "chatgpt",
      "gpt",
      "llm",
      "ai agent",
      "ai agents",
      "artificial intelligence",
      "machine learning",
      "модель",
      "агент",
      "генеративн",
      "автоматизац",
      "productivity",
      "workflow",
      "business applications",
      "internal processes",
      "copilot",
      "assistant",
    ],
    exclude: [
      ...COMMON_EXCLUDE,
      "криптовалют",
    ],
    feeds: [
      { name: "OpenAI News", weight: 10, url: "https://openai.com/news/rss.xml" },
      { name: "Anthropic News", weight: 10, url: "https://www.anthropic.com/news/rss.xml" },
      { name: "Google DeepMind Blog", weight: 10, url: "https://deepmind.google/discover/blog/rss.xml" },
      { name: "Microsoft AI Blog", weight: 9, url: "https://blogs.microsoft.com/ai/feed/" },
      { name: "TechCrunch AI", weight: 9, url: "https://techcrunch.com/category/artificial-intelligence/feed/" },
      { name: "The Verge AI", weight: 8, url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml" },
      { name: "VentureBeat AI", weight: 8, url: "https://venturebeat.com/category/ai/feed/" },
    ],
  },
};

module.exports = { SOURCES };
